version: '3.9'

services:
  scrapy:
    build: 
      context: .
      dockerfile: Dockerfile
    image: scrapy:2.6.1
    container_name: my_scrapy
    volumes:
      - $PWD/app:/usr/src/app
    tty: true
